[versions]
kotlin-logging = "7.0.14"
junit-jupiter = "6.0.2"
kerby-asn1 = "2.1.1"
klaxon = "5.6"
protobuf = "4.33.4"

kover-plugin = "0.9.4"
ktlint-plugin = "14.0.1"
nexus-plugin = "2.0.0"
versions-plugin = "0.53.0"
testlogger-plugin = "4.0.0"

result-monad = "1.4.0"

[libraries]
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
kerby-asn1 = { module = "org.apache.kerby:kerby-asn1", version.ref = "kerby-asn1" }
klaxon = { module = "com.beust:klaxon", version.ref = "klaxon" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }

result-monad = { module = "org.erwinkok.result:result-monad", version.ref = "result-monad" }

[plugins]
build-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover-plugin" }
build-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
build-nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-plugin" }
build-versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
build-testlogger = { id = "com.adarshr.test-logger", version.ref = "testlogger-plugin" }
